### ISSUE TITLE
doesnt remap everything on windows, but works perfectly on linux

### ISSUE THREAD

**Issue by mr-nv** [1fxe/Recaf4Forge#10]
tested on recaf 2.19.5 - 2.21.2
1.12.2 minecraft
![image](https://user-images.githubusercontent.com/31269663/137153508-f934fa13-c056-45eb-a2bc-6e47c5b6a826.png)

**Comment by 1fxe** [comment]
Thanks for opening the issue ill see if I can fix

**Comment by 1fxe** [comment]
https://github.com/1fxe/Recaf4Forge/releases/tag/v1.2.3 if you have time can you check this and see if it fixes
